#!/bin/sh
# FIXME 
JAR=~/src/sctags/target/scala-2.11/sctags_2.11-1.0.jar

if [[ -z $SCALA_LIB ]]; then
    SCALA_BIN=$(which scala)
    SCALA_HOME=$(dirname $SCALA_BIN)
    SCALA_LIB="$SCALA_HOME/../lib"
fi
exec java -Xbootclasspath/a:$SCALA_LIB/scala-compiler.jar:$SCALA_LIB/scala-library.jar:$SCALA_LIB/scala-reflect.jar -jar $JAR "$@"
